//
//  LoginSceneInteractor.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginSceneBusinessLogic {
    func doSomeLogic(request: LoginScene.Something.Request)
}

protocol LoginSceneDataStore {
    //var name: String { get set }
}

class LoginSceneInteractor: LoginSceneDataStore {
    
    var presenter: LoginScenePresentationLogic?
    var worker: LoginSceneWorker?
    
    //MARK: DataStore
    //var name: String = ""

    // MARK: Do stuff
    
    private func doSomething() {
        let request = LoginScene.Something.Request()
        self.doSomeLogic(request: request)
    }

}

extension LoginSceneInteractor: LoginSceneBusinessLogic {
    
    func doSomeLogic(request: LoginScene.Something.Request) {
        worker = LoginSceneWorker()
        worker?.doSomeWork()
        
        let response = LoginScene.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
