//
//  LoginSceneViewController.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginSceneDisplayLogic: class {
    func displaySomething(viewModel: LoginScene.Something.ViewModel)
}

class LoginSceneViewController: UIViewController {
    var interactor: LoginSceneBusinessLogic?
    var router: (NSObjectProtocol & LoginSceneRoutingLogic & LoginSceneDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup
  
    private func setup() {
        
        LoginSceneConfigurator.sharedInstance.configure(viewController: self)
        
    }
  
    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doOnDidLoad()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doOnDidLoad() {
        let request = LoginScene.Something.Request()
        interactor?.doSomeLogic(request: request)
    }
  
 }

extension LoginSceneViewController: LoginSceneDisplayLogic {
    
    func displaySomething(viewModel: LoginScene.Something.ViewModel) {
        
    }

}
