//
//  ObserverSceneViewController.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MessageUI
import Combine

protocol ObserverSceneDisplayLogic: class {
    func displaySomething(viewModel: ObserverScene.Something.ViewModel)
}

class StringSubscriber: Subscriber {
    typealias Input = String
    typealias Failure = ObserverScene.MyError

    func receive(subscription: Subscription) {
        subscription.request(.max(2)) //backpressure
    }
    
    func receive(_ input: String) -> Subscribers.Demand {
        print("Received value:", input)
        return .none
    }
    
    func receive(completion: Subscribers.Completion<ObserverScene.MyError>) {
        print("Completed")
    }
    
    
    
    
}


class ObserverSceneViewController: UIViewController {
    var interactor: ObserverSceneBusinessLogic?
    var router: (NSObjectProtocol & ObserverSceneRoutingLogic & ObserverSceneDataPassing)?
    
    private var currentTFTag: Int = 0

    @IBOutlet weak var vcTF1: UITextField!
    @IBOutlet weak var vcTF2: UITextField!
    @IBOutlet weak var vcTF3: UITextField!
    @IBOutlet weak var vcTF4: UITextField!
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup
  
    private func setup() {
        
        ObserverSceneConfigurator.sharedInstance.configure(viewController: self)
        
    }
  
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doOnDidLoad()
    }

    // MARK: Do something

    func doOnDidLoad() {
        
        if #available(iOS 12.0, *) {
            self.vcTF1.textContentType = .oneTimeCode
            self.vcTF1.keyboardType = .numberPad
        }

        self.vcTF1.delegate = self
        self.vcTF2.delegate = self
        self.vcTF3.delegate = self
        self.vcTF4.delegate = self
        
//        runObserver()
//        runObserver2()
//        runObserver3()
        runObserver4()

    }
    
    private func runObserver() {
        let notification = Notification.Name("NotificationO1")
        let center = NotificationCenter.default
        
        /*let observer*/ _ = center.addObserver(forName: notification, object: nil, queue: OperationQueue()) { (notification) in
            print("Notification received")
        }
        
        center.post(name: notification, object: nil)
        
        center.removeObserver(notification)
    }
    
    private func runObserver2() {
        let notification = Notification.Name("NotificationO2")
        let publisher = NotificationCenter.default.publisher(for: notification, object: nil)
        let subscription = publisher.sink { _ in
            print("Notification received 2")
        }
        subscription.cancel()
        NotificationCenter.default.post(name: notification, object: nil)

    }

    private func runObserver3() {
        let publisher = ["A", "B", "C","D","E","F","G","H","I","J","K"].publisher
        let subscriber = StringSubscriber()
        //publisher.subscribe(subscriber)
        
    }

    private func runObserver4() { //Subjects
        let subscriber = StringSubscriber()
        let subject = PassthroughSubject<String, ObserverScene.MyError>()
        subject.subscribe(subscriber)
        subject.send("L")
        subject.send("ABC")
        subject.send("E")
    }

    private func fillCodeFields(codeCharacter: String) {
        currentTFTag += 1
        if currentTFTag > 1, let currentTF = view.viewWithTag(currentTFTag) as? UITextField {
            currentTF.text = codeCharacter
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                self.setActiveTextField(currentTF)
            }
        }
    }
    
    private func setActiveTextField(_ textField: UITextField) {
        let nextTag = textField.tag + 1

        if let nextResponder = textField.superview?.viewWithTag(nextTag) {
            nextResponder.becomeFirstResponder()
        } else {
            textField.resignFirstResponder()
            print("Finish code entering")
        }
    }

    @IBAction func buttonClicked(_ sender: UIButton) {
        let messageVC = MFMessageComposeViewController()
               messageVC.body = "Verification code: 1234";
               messageVC.recipients = ["89024672586"]
               messageVC.messageComposeDelegate = self
               self.present(messageVC, animated: true, completion: nil)
    }
}

extension ObserverSceneViewController: MFMessageComposeViewControllerDelegate {
    
    func messageComposeViewController(_ controller: MFMessageComposeViewController, didFinishWith result: MessageComposeResult) {
        switch (result) {
        case .cancelled:
            print("Message was cancelled")
            dismiss(animated: true, completion: nil)
        case .failed:
            print("Message failed")
            dismiss(animated: true, completion: nil)
        case .sent:
            print("Message was sent")
            dismiss(animated: true, completion: nil)
        default:
            break
        }
    }
    
}

extension ObserverSceneViewController: ObserverSceneDisplayLogic {
    
    func displaySomething(viewModel: ObserverScene.Something.ViewModel) {
        
    }

}

extension ObserverSceneViewController: UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        self.setActiveTextField(textField)
        return true
    }
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        
        if textField.tag == 1, string.count > 0 {
            self.fillCodeFields(codeCharacter: string)
        }
        
        // get the current text, or use an empty string if that failed
        let currentText = textField.text ?? ""

        // attempt to read the range they are trying to change, or exit if we can't
        guard let stringRange = Range(range, in: currentText) else { return false }

        // add their new text to the existing text
        let updatedText = currentText.replacingCharacters(in: stringRange, with: string)

        // make sure the result is under 1 character
        return updatedText.count <= 1
    }
}

