//
//  ObserverSceneConfigurator.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

class ObserverSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ObserverSceneConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ObserverSceneViewController) {
        let interactor = ObserverSceneInteractor()
        let presenter = ObserverScenePresenter()
        let router = ObserverSceneRouter()
        let worker = ObserverSceneWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
