//
//  ObserverScenePresenter.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObserverScenePresentationLogic {
    func presentSomething(response: ObserverScene.Something.Response)
}

class ObserverScenePresenter: ObserverScenePresentationLogic {
    weak var viewController: ObserverSceneDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ObserverScene.Something.Response) {
        let viewModel = ObserverScene.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
}
