//
//  ObserverSceneInteractor.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObserverSceneBusinessLogic {
    func doSomeLogic(request: ObserverScene.Something.Request)
}

protocol ObserverSceneDataStore {
    //var name: String { get set }
}

class ObserverSceneInteractor: ObserverSceneDataStore {
    
    var presenter: ObserverScenePresentationLogic?
    var worker: ObserverSceneWorker?
    
    //MARK: DataStore
    //var name: String = ""

    // MARK: Do stuff
    
    private func doSomething() {
        let request = ObserverScene.Something.Request()
        self.doSomeLogic(request: request)
    }

}

extension ObserverSceneInteractor: ObserverSceneBusinessLogic {
    
    func doSomeLogic(request: ObserverScene.Something.Request) {
        worker = ObserverSceneWorker()
        worker?.doSomeWork()
        
        let response = ObserverScene.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
