//
//  ObserverSceneInteractor.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObserverSceneBusinessLogic {
    func runObserver(request: ObserverScene.Observer.Request)
}

protocol ObserverSceneDataStore {
    //var name: String { get set }
}

class ObserverSceneInteractor: ObserverSceneDataStore {
    
    var presenter: ObserverScenePresentationLogic?
    var worker: ObserverSceneWorker?
    
    //MARK: DataStore
    //var name: String = ""

    // MARK: Do stuff
    
}

extension ObserverSceneInteractor: ObserverSceneBusinessLogic {
    
    func runObserver(request: ObserverScene.Observer.Request) {
        worker?.runObserver()
        
        let response = ObserverScene.Observer.Response()
        presenter?.presentObserver(response: response)
    }

}
