//
//  ObserverSceneModels.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ObserverScene {
    
    enum MyError: Error {
        case SomeError
    }
    
  // MARK: Use cases
  
    enum Observer {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    
}
