//
//  StartSceneConfigurator.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

class StartSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = StartSceneConfigurator()
    
    // MARK: Configuration
    
    func configure() -> StartSceneBusinessLogic {
        let interactor = StartSceneInteractor()
        let router = StartSceneRouter()
        let worker = StartSceneWorker()
        interactor.worker = worker
        interactor.router = router
        router.dataStore = interactor
        return interactor
    }
}
