//
//  StartSceneRouter.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StartSceneRoutingLogic {
    func routeToLoginScene()
    func routeToObserverScene()
}

protocol StartSceneDataPassing {
    var dataStore: StartSceneDataStore? { get }
}

class StartSceneRouter: NSObject, StartSceneRoutingLogic, StartSceneDataPassing {
    var dataStore: StartSceneDataStore?

    // MARK: LoginScene
    func routeToLoginScene() {
        let destinationVC: LoginSceneViewController = LoginSceneViewController(nibName: "LoginSceneViewController", bundle: nil)
        var destinationDS = destinationVC.router!.dataStore!
        passDataToLoginScene(source: dataStore!, destination: &destinationDS)
        navigateToLoginScene(destination: destinationVC)
    }
    func passDataToLoginScene(source: StartSceneDataStore, destination: inout LoginSceneDataStore) {
    }
    func navigateToLoginScene(destination: LoginSceneViewController) {
        dataStore?.navigationController?.initRootViewController(vc: destination)
    }

    // MARK: ObserverScene
    func routeToObserverScene() {
        let destinationVC: ObserverSceneViewController = ObserverSceneViewController(nibName: "ObserverSceneViewController", bundle: nil)
        var destinationDS = destinationVC.router!.dataStore!
        passDataToLoginScene(source: dataStore!, destination: &destinationDS)
        navigateToLoginScene(destination: destinationVC)
    }
    func passDataToLoginScene(source: StartSceneDataStore, destination: inout ObserverSceneDataStore) {
    }
    func navigateToLoginScene(destination: ObserverSceneViewController) {
        dataStore?.navigationController?.initRootViewController(vc: destination)
    }
    
}
