//
//  StartSceneInteractor.swift
//  CombineApp1
//
//  Created by Mac on 02.11.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartSceneBusinessLogic {
    func launch(from navigationController: UINavigationController?)
}

protocol StartSceneDataStore {
    var navigationController: UINavigationController? { get set }
}

class StartSceneInteractor: StartSceneDataStore {
    
    var router: (NSObjectProtocol & StartSceneRoutingLogic & StartSceneDataPassing)?
    var worker: StartSceneWorker?
    
    //MARK: DataStore
    var navigationController: UINavigationController?

}

extension StartSceneInteractor: StartSceneBusinessLogic {
    
    func launch(from navigationController: UINavigationController?) {
        self.navigationController = navigationController
        
        //test
        UserDefaults.standard.set(true, forKey: UserDefaults.Keys.Token)
        
        let hasToken: Bool = worker?.checkToken() ?? false
        
        print(hasToken)
        
        if hasToken {
            router?.routeToObserverScene()
        } else {
            router?.routeToLoginScene()
        }
        
    }

}
